title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educaci贸n tecnol贸gica

baseurl: "/portafolio_grupo_D_uc/jonathan-alvarez"
url: "https://digitec-conexion.github.io"

remote_theme: pages-themes/hacker@v0.2.0

# Plugins esenciales
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# Configuraci贸n de procesamiento
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Carga de datos
data_dir: "jonathan-alvarez/_data"

include:
  - "jonathan-alvarez/_data/education.json"
  - "jonathan-alvarez/_data/experience.json"
  - "jonathan-alvarez/_data/projects.json"
  - "jonathan-alvarez/_data/skills.json"

# Social Media
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe
  github: jthnconti

# Configuraci贸n de GitHub Pages
github: [metadata]